name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        id: docker_login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
            MODEL_NAME=${{ secrets.MODEL_NAME }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/digitaltwin:${{ steps.docker_login.outputs.time }}"
